[WIP] Add gRPC
podder-ai/podder-task pull request #16
Opened 2018-11-15 03:50 UTC by takp

2018-11-16 04:54 UTC, takp commented on framework/api/task_api.py
> +class TaskApi(pipeline_framework_pb2_grpc.TaskApiServicer):
gRPC経由で、 `TaskApi` が処理を受付ける窓口になっています

2018-11-16 05:11 UTC, takaaki-mizuno requested changes

2018-11-16 05:11 UTC, takaaki-mizuno commented on framework/api/grpc_server.py
> +        server.stop(0)
grpc サーバの実装って、これで良いのかな？
これ停止したときとかってどうやって監視するかんじですか。

2018-11-20 04:50 UTC, takp commented on framework/api/grpc_server.py
> +GRPC_PID_FILE = '/var/run/grpc_server.pid'
PIDファイルをここに設置するようにしました

2018-11-20 04:51 UTC, takp commented on Dockerfile
> +CMD python framework/api/grpc_server.py; tail -f $GRPC_ERROR_LOG
エラーログの内容を出力させるようにしてます

2018-11-20 04:51 UTC, takp commented on framework/api/grpc_server.py
> +        server.stop(0)
`daemon.DaemonContext` でプロセスをデーモン化させるようにしました

2018-11-20 10:52 UTC, takp commented
- Max worker と port 番号を環境変数などで指定できるように変更

2018-11-21 02:43 UTC, takp commented
- [ ] Max worker と port 番号を環境変数などで指定できるように変更
- [ ] pid ファイル名を "poc_base.pid" に変更
- [ ] Dockerfile CMDで 正常ログとエラーログの両方を読むように変更

2018-11-21 04:13 UTC, takaaki-mizuno approved these changes

2018-11-21 04:13 UTC, merged