Issues/507/log format
podder-ai/podder-task pull request #45
Opened 2019-03-08 10:24 UTC by lastshogun13

https://github.com/Innovatube/podder-task-management/issues/507
ログフォーマット対応です。
podder-task-baseのプルリクエストをしてあるので、事前にそれを組み込んでからこちらのマージをお願いします。
podder-task-baseはバージョン0.0.9になることを想定してバージョン番号を記載しています。

2019-03-12 10:30 UTC, lastshogun13 commented
podder-task-baseに新しいプルリクエストを出したため、podder-task-baseのバージョンを0.1.1にしています。また、ログのフォーマット部分に呼び出し場所情報を追加しました。

2019-03-13 02:32 UTC, takp requested changes

2019-03-13 02:32 UTC, takp commented on log.yml
> +task_name: writer-task
`podder-task` が正しそうです

2019-03-13 02:33 UTC, takp commented
あと、READMEのlogger部分も更新が必要なので、お願いします

2019-03-13 03:27 UTC, lastshogun13 commented on log.yml
> +task_name: writer-task
失礼しました。指摘の通りです。修正しておきました。

2019-03-13 06:39 UTC, takp commented
@lastshogun13 
>あと、READMEのlogger部分も更新が必要なので、お願いします

すみません、上記のコメント気づかれてないようなのですが、READMEの修正もお願いしたいです。

2019-03-13 07:56 UTC, lastshogun13 commented
フォーマットをLTSVにして、マイクロ秒を正常に出力するようにしました。
READMEの修正をしました。

2019-03-13 09:43 UTC, takp commented on log.yml
> +task_log_format: "time:[%(time)s]	name:%(name)s	taskname:%(taskname)s	scriptinfo:[%(scriptinfo)s]	loglevel:%(levelname)s	progresstime:%(progresstime)s	tasktime:%(tasktime)s	message:[%(message)s]"
こちらもタブの表記を `\t` に合わせて頂きたいです

2019-03-13 10:14 UTC, lastshogun13 commented on log.yml
> +task_log_format: "time:[%(time)s]	name:%(name)s	taskname:%(taskname)s	scriptinfo:[%(scriptinfo)s]	loglevel:%(levelname)s	progresstime:%(progresstime)s	tasktime:%(tasktime)s	message:[%(message)s]"
はい。こちらも修正しました。

2019-03-13 11:06 UTC, takp approved these changes
LGTM

2019-03-13 11:06 UTC, merged