Pa 236/task initializer
podder-ai/podder-task pull request #49
Opened 2019-03-26 07:07 UTC by lastshogun13

https://nexusfrontiertech.atlassian.net/browse/PA-205
この件についての修正です。

ファイルがかなりスッキリしました。

2019-03-26 08:23 UTC, takp requested changes

2019-03-26 08:23 UTC, takp commented on Dockerfile
> +    GRPC_MAX_WORKERS=10 \
これって何でここに追加されたんですか？
なぜ変更されたのか意図が分からないので、こういう変更は適宜コメント付けて頂きたいです（プルリク出した後にコードにコメント付けてもらえるとレビューする際にとても助かります）

2019-03-26 08:23 UTC, takp commented on requirements.txt
>  SQLAlchemy==1.2.17
今回の変更後もこれらって必要になりそうでしょうか？
もし必要なければ削除してしまう方が良いのかな、と思いました。

2019-03-26 08:23 UTC, takp commented on Dockerfile
> +RUN python -m podder_task_base.task_initializer init /usr/local/poc_base sample-task
`sample-task` というのは…（？）

2019-03-27 13:09 UTC, lastshogun13 commented on Dockerfile
> +RUN python -m podder_task_base.task_initializer init /usr/local/poc_base sample-task
指摘ありがとうございます。引数の書式自体も最新で変えていたので、そこも合わせて修正しました。

2019-03-27 14:19 UTC, lastshogun13 commented on Dockerfile
> +    GRPC_MAX_WORKERS=10 \
sensor、writerにあった環境引数なので、それにあわせて付けた形になります。

2019-03-27 14:20 UTC, lastshogun13 commented
requirements.txt については、中身からの状態でファイルだけ残しておくのがいいかなと思っています。
これは、ユーザー（利用する開発者）が、pipで何か追加したい場合に使えるファイルとして残しておくという考え方になります。

2019-03-28 02:45 UTC, takp reviewed
質問だけさせていただきました

2019-03-28 02:45 UTC, takp commented on Dockerfile
> +    GRPC_MAX_WORKERS=10 \
あ、なるほど！そういえばありましたね。承知しました。

2019-03-28 02:45 UTC, takp commented on Dockerfile
> +RUN python -m podder_task_base.task_initializer init podder-task
一応確認したいのですが、 `podder-task` って固定の名称で大丈夫でしょうか？
`podder task add` する際に、違う名前を付けても大丈夫かどうかが気になりました。例えば `scanner-task` 等の名前を付けた時とかです。
あ、ひょっとして、 `podder task add` の際にこの部分もテンプレートから作成して変更する事になるイメージでしょうか？

2019-03-28 02:50 UTC, lastshogun13 commented
すみません。間違えて、resolveボタンを押して、@takpのコメントが見えなくなってしまったので、ここで返事を書きます。
TaskInitializerの引数で podder-task になっている箇所は、この後 task add の実装で動的に書き換える必要がある箇所になります。

2019-03-28 03:00 UTC, takp commented
@lastshogun13 そういう事ですね、では認識同じなので了解です！ありがとうございます

2019-03-28 03:01 UTC, takp approved these changes
LGTM 👍

2019-03-28 03:01 UTC, merged